# Generated by Django 5.1 on 2026-06-18 12:29

import core.services.upload_photos
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_currencymodel_options_and_more'),
        ('listings', '0008_alter_listingmodel_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingmodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='currency.currencymodel'),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='edit_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='initial_currency_rate',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='listing_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.services.upload_photos.upload_photo_listing, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='price_uah',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='views_day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='views_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='views_week',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)]),
        ),
    ]
