# Generated by Django 5.1 on 2026-06-18 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('brand__name', 'model_name__name', 'body_type')},
        ),
        migrations.AlterModelOptions(
            name='modelname',
            options={'ordering': ('brand__name', 'name')},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.brand'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.modelname'),
        ),
        migrations.AddConstraint(
            model_name='carmodel',
            constraint=models.UniqueConstraint(fields=('brand', 'model_name', 'body_type'), name='unique_car_configuration'),
        ),
        migrations.AddConstraint(
            model_name='modelname',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='unique_model_name_per_brand'),
        ),
    ]
