# Generated by Django 5.1 on 2026-06-18 12:29

import core.services.upload_photos
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_password_alter_blacklistmodel_table'),
        ('users_auth', '0002_alter_userrolemodel_options_alter_userrolemodel_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistmodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='blacklistmodel',
            name='added_at',
        ),
        migrations.AlterField(
            model_name='blacklistmodel',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_blacklist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blacklistmodel',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.services.upload_photos.upload_avatar, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=55, validators=[django.core.validators.RegexValidator("^[A-ZА-ЯІЇЄҐ][a-zA-Zа-яА-ЯіїєґІЇЄҐʼ\\'-]{1,54}$", 'Name must start with an uppercase letter and contain 2-55 characters.')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=55, validators=[django.core.validators.RegexValidator("^[A-ZА-ЯІЇЄҐ][a-zA-Zа-яА-ЯіїєґІЇЄҐʼ\\'-]{1,54}$", 'Name must start with an uppercase letter and contain 2-55 characters.')]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users_auth.userrolemodel'),
        ),
    ]
