# Generated by Django 5.1 on 2026-06-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrolemodel',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='userrolemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userrolemodel',
            name='name',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
