# Generated by Django 5.1 on 2026-06-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencymodel',
            options={'ordering': ('currency_code',)},
        ),
        migrations.AlterUniqueTogether(
            name='currencymodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='currencymodel',
            name='currency_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='currencymodel',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='currencymodel',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='currency_rate_positive'),
        ),
    ]
