# Generated by Django 5.1 on 2026-06-18 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmodel_chat_id_chatmodel_created_at_and_more'),
        ('listings', '0009_alter_listingmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmodel',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='chatmodel',
            name='chat_id',
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='body',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='listings.listingmodel'),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatmodel',
            index=models.Index(fields=['listing', 'created_at'], name='chat_listing_fc8d18_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmodel',
            index=models.Index(fields=['user', 'created_at'], name='chat_user_id_995d74_idx'),
        ),
    ]
